version: '3.9'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_vol:/var/lib/mysql

  adminer:
    image: adminer:${ADMINER_VERSION}
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  mysql_vol:
