version: '3.9'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - school_book_storage_network

  adminer:
    image: adminer:${ADMINER_VERSION}
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - school_book_storage_network

volumes:
  mysql_vol:

networks:
  school_book_storage_network:
    name: school_book_storage_network
